CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY IDENTITY(1,1),
    FLOOR_NO INT NOT NULL,
    SEAT_NO NVARCHAR(10) NOT NULL
);

CREATE TABLE Employee (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME NVARCHAR(50),
    EMAIL NVARCHAR(100),
    FLOOR_SEAT_SEQ INT,
    FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);
